# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "mamo-payment-app"
client_id = "0e2f137681cd5353bf3566ec0d880b9c"
application_url = "https://mamo-app.dev-test.pro"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://mamo-app.dev-test.pro/auth/callback",
  "https://mamo-app.dev-test.pro/auth/shopify/callback",
  "https://mamo-app.dev-test.pro/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mamo-payment-test-store.myshopify.com"
