# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Mamo Payments App"
client_id = "0e2f137681cd5353bf3566ec0d880b9c"
application_url = "https://7af0-194-31-212-75.ngrok-free.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_gateways,write_payment_sessions"

[auth]
redirect_urls = [
  "https://7af0-194-31-212-75.ngrok-free.app/auth/callback",
  "https://7af0-194-31-212-75.ngrok-free.app/auth/shopify/callback",
  "https://7af0-194-31-212-75.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://plugins-shopify.business.mamopay.com/webhooks"
  customer_data_request_url = "https://plugins-shopify.business.mamopay.com/webhooks"
  shop_deletion_url = "https://plugins-shopify.business.mamopay.com/webhooks"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mamo-test-dmytro.myshopify.com"
